### ISSUE TITLE
The server configuration Id change everytime jenkins settings are saved

### ISSUE THREAD

**Issue by lionelraeymaekers** [xpandit/xrayjenkins#14]
The hidden textbox containing the server id was removed in the latest release, causing the ID to be regenerated on every save of the settings

https://github.com/xpandit/xrayjenkins/blob/f56589f52d8926db350e383b1b8c826b6de7bfad/src/main/resources/com/xpandit/plugins/xrayjenkins/model/ServerConfiguration/config.jelly#L10

Missing
`<f:textbox value="${serverInstances.configID}" style="display:none" />`

**Comment by Russell616** [comment]
Hi lionelraeymaekers!

Thank you very much for reporting this issue, I was able to recreate this issue in the plugin's latest version.
I created a new entry in our Issue Tracker: https://jira.xpand-it.com/browse/XRAYJENKINS-73

Please notice that this repository was moved to [here](https://github.com/jenkinsci/xray-connector-plugin), so the fix and the Pull Request will be created over there.

I will close this issue, however, feel free to continue this discussion in the other repository :)
